# Generated by Django 5.0.7 on 2024-08-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuron', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depend',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='depend',
            name='views_count',
            field=models.BooleanField(),
        ),
    ]
